# Generated by Django 3.0.6 on 2020-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POLL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('yes', models.CharField(max_length=3)),
                ('No', models.CharField(max_length=2)),
            ],
        ),
    ]
