# Generated by Django 3.0.6 on 2020-06-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_spoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoll',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
